services:
  web:
    build:
      context: ./web
      dockerfile: ./.nixpacks/Dockerfile
      args:
        CI: "true"
        NIXPACKS_METADATA: "node"
        NODE_ENV: "production"
        NPM_CONFIG_PRODUCTION: "false"
    ports:
      - "5174:5173"
    networks:
      frontend:
      backend:
    volumes:
      - ./web:/app
    environment:
      - PUBLIC_CRITINO_URL
      - PUBLIC_CRITINO_API_URL
      - PUBLIC_CRITINO_API_KEY
      - PUBLIC_SUPABASE_URL
      - PUBLIC_SUPABASE_ANON_KEY
      - PRIVATE_SUPABASE_SERVICE_ROLE
      - PRIVATE_STRIPE_API_KEY
      - PUBLIC_API_URL
      - PRIVATE_API_URL
    env_file: ./web/.env
  api:
    restart: always
    build:
      context: ./services/api
      dockerfile: ./Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./services/api:/app
    networks:
      backend:
    env_file: ./services/api/.env
    command: poetry run fastapi dev src --host 0.0.0.0 --port 8001 --reload

networks:
  frontend:
  backend:
